spring:
  application:
    name: realtime-event-sourcing-chat
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/resc_chat?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:resc_app}
    password: ${DB_PASSWORD:resc_app_password}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
  logging:
  level:
    root: info
    org.springframework: warn
    org.hibernate: warn
    com.zaxxer.hikari: warn
    org.flywaydb: info
    com.sokind.chat: debug

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true

app:
  event-sourcing:
    restore-default-message-limit: ${RESTORE_DEFAULT_MESSAGE_LIMIT:100}
    snapshot-event-interval: ${SNAPSHOT_EVENT_INTERVAL:100}
